<?xml version="1.0" encoding="utf-8"?><Database Name="ERSCDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSC-PC;Initial Catalog=ERSCDB;Integrated Security=True" SettingsObjectName="ERSC.Properties.Settings" SettingsPropertyName="ERSCDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TbTaskListFirst" Member="TbTaskListFirsts">
    <Type Name="TbTaskListFirst">
      <Column Name="ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Search_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Point_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_ID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Probability" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAssigned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TbPointFirst_TbTaskListFirst" Member="TbPointFirst" ThisKey="Point_ID" OtherKey="Point_ID" Type="TbPointFirst" IsForeignKey="true" />
      <Association Name="TbRescueFirst_TbTaskListFirst" Member="TbRescueFirst" ThisKey="Rescue_ID" OtherKey="Rescue_ID" Type="TbRescueFirst" IsForeignKey="true" />
      <Association Name="TbSearchFirst_TbTaskListFirst" Member="TbSearchFirst" ThisKey="Search_ID" OtherKey="Search_ID" Type="TbSearchFirst" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbPointFirst" Member="TbPointFirsts">
    <Type Name="TbPointFirst">
      <Column Name="Point_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Point_IntID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_ParentID" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Point_TopCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_LeftCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_TopProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Point_LeftProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Poin_Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Point_NumVictim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_TimeToBeDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_RescueLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_CreatPoint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_IsAllocatedSTeam" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_IsAllocatedRTeam" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_StartSearchDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_EndSearchDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_StartRescueDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_EndRescueDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TbPointFirst_TbTaskListFirst" Member="TbTaskListFirsts" ThisKey="Point_ID" OtherKey="Point_ID" Type="TbTaskListFirst" />
    </Type>
  </Table>
  <Table Name="dbo.TbRescueFirst" Member="TbRescueFirsts">
    <Type Name="TbRescueFirst">
      <Column Name="Rescue_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rescue_IntID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_TopCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_LeftCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_TopProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rescue_LeftProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rescue_State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TbRescueFirst_TbTaskListFirst" Member="TbTaskListFirsts" ThisKey="Rescue_ID" OtherKey="Rescue_ID" Type="TbTaskListFirst" />
    </Type>
  </Table>
  <Table Name="dbo.TbSearchFirst" Member="TbSearchFirsts">
    <Type Name="TbSearchFirst">
      <Column Name="Search_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Search_IntID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_TopCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_LeftCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_TopProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Search_LeftProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Search_State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TbSearchFirst_TbTaskListFirst" Member="TbTaskListFirsts" ThisKey="Search_ID" OtherKey="Search_ID" Type="TbTaskListFirst" />
    </Type>
  </Table>
  <Table Name="dbo.TbPoint" Member="TbPoints">
    <Type Name="TbPoint">
      <Column Name="Point_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Point_IntID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_ParentID" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Point_TopCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_LeftCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_TopProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Point_LeftProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Poin_Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Point_NumVictim" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_TimeToBeDone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_RescueLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_CreatPoint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point_IsAllocatedSTeam" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_IsAllocatedRTeam" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_StartSearchDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_EndSearchDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_StartRescueDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Point_EndRescueDoing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TbPoint_TbTaskList" Member="TbTaskLists" ThisKey="Point_ID" OtherKey="Point_ID" Type="TbTaskList" />
    </Type>
  </Table>
  <Table Name="dbo.TbRescue" Member="TbRescues">
    <Type Name="TbRescue">
      <Column Name="Rescue_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rescue_IntID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_TopCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_LeftCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_TopProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rescue_LeftProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rescue_State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TbRescue_TbTaskList" Member="TbTaskLists" ThisKey="Rescue_ID" OtherKey="Rescue_ID" Type="TbTaskList" />
    </Type>
  </Table>
  <Table Name="dbo.TbSearch" Member="TbSearches">
    <Type Name="TbSearch">
      <Column Name="Search_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Search_IntID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_TopCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_LeftCoordinate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_TopProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Search_LeftProjection" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Search_State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_Unit" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TbSearch_TbTaskList" Member="TbTaskLists" ThisKey="Search_ID" OtherKey="Search_ID" Type="TbTaskList" />
    </Type>
  </Table>
  <Table Name="dbo.TbTaskList" Member="TbTaskLists">
    <Type Name="TbTaskList">
      <Column Name="ID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Search_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Point_ParentID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Point_ID" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Rescue_ID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Probability" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAssigned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TbPoint_TbTaskList" Member="TbPoint" ThisKey="Point_ID" OtherKey="Point_ID" Type="TbPoint" IsForeignKey="true" />
      <Association Name="TbRescue_TbTaskList" Member="TbRescue" ThisKey="Rescue_ID" OtherKey="Rescue_ID" Type="TbRescue" IsForeignKey="true" />
      <Association Name="TbSearch_TbTaskList" Member="TbSearch" ThisKey="Search_ID" OtherKey="Search_ID" Type="TbSearch" IsForeignKey="true" />
    </Type>
  </Table>
</Database>